project:
  type: book
  output-dir: docs

book:
  title: "FA23-Cox Proportional"
  author: "Norah Jones"
  date: "10/8/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - methods.qmd
    - Results_and_Discussion_3.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

