---
title: "Cox Proportional Hazards Model"
author: "Ivan Burgos, Vladimir Dragomirov"
format: revealjs
---

## Cox Proportional Hazard Model

::: incremental
-   Developed by Sir David R Cox, a british statistician, in 1972

-   Also called Cox Regression

-   Used to investigate time to event data, e.g. time until patient dies, time until part malfunctions, time until decision is made, etc.

-   The field of Survival Analysis works with a lot of time to event data, and makes a lot of use of the Cox Proportional Hazards Model and its extensions
:::

## Prior to Cox PH Model

**Log Rank Test** - compares groups, testing a null hypothesis that there is no difference between groups. Limitations: ability to handle multiple variables, abilit to quantify a difference between groups

**Kaplan-Meier Survival Curve** - very simple to implement, graphs how many are alive in each group at what time. Limitations: ability to handle more than a few varieables and any non-categorical variables, no mathematical function to describe the data, can not estimate a ratio of the hazards between groups,

## Example Kaplan-Meier Survival Curve

```{r}
#| echo: false
#import dataset
heart_transplant <- read.csv("./heart_transplant.csv")

#load neaded libraries
library(survival)

#generate numeric column for survived from character
heart_transplant$survived2 <- as.numeric(ifelse(heart_transplant$survived=="dead",1,0))

#generate kaplan meier model
km.model <- survfit(Surv(heart_transplant$survtime,heart_transplant$survived2)~1)

#plot model
plot(km.model, conf.int=F, xlab = "Time (days)", ylab = "Percent Alive", main="Kaplan Meier Model Heart Transplant Candidatae Survival")
```

## Cox Proportional Hazards Model

$h_0(t)$ is the baseline hazard - for example what is your baseline hazard (risk, chance) of dying

$h(t)$ is the hazard at time t for the group of interest.

This hazard $h(t)$ can be modeled as the baseline hazard times an exponential function describing the affect of the predictor variables $$
h(t)=h_0(t) \times exp (\beta_1X_{1} + \beta_{2}X_{2} + \dots + \beta_n X_{n})
$$

## Cox Proportional Hazards Model

$$ h(t)=h_0(t) \times exp (\beta_1X_{1} + \beta_{2}X_{2} + \dots + \beta_n X_{n}) $$

Dividing both sides by the baseline hazard we get the hazard ratio

$$
h(t)/h_0(t)= exp (\beta_1X_{1} + \beta_{2}X_{2} + \dots + \beta_n X_{n})
$$

Taking the natural log yields a formula that has some similarity to linear regression. The log of the hazard ratio has a linear relationship to the predictor variables.

$$
ln(h(t)/h_0(t))= \beta_1X_{1} + \beta_{2}X_{2} + \dots + \beta_n X_{n}
$$

## Cox PHM Assumptions -  Assumptions in common with many other models  {.smaller}

**Linearity** - model assumes the log of the hazard ratio is linearly proportional to the predictor variables. Check for this with plot of residuals, similar to how other models check for this. The methods for handling data that violates this assumption is same as it is for other forms of regression

**Observations are independent** - the survival of one person is independent of the survival of another person. Example of when this may be more of an issue, less common hereditary health conditions, study participants may be related.

**Censoring is non-informative** - those that are censored, example leave the study, are just as likely to experience the event, example death, as those that finish the study.

## Cox PHM Assumptions - more specific to this model  {.smaller}

**Proportional Hazards** - model assumes the hazards are proportional.

-   check this with Schoenffieldt test

-   handle violations with: stratification (we will see this in our example), or introduce time dependent parameters "(x\*t)" instead of simply "x"

**Independent variables are not changed over time** - example people moved from one cohort of the study to another, dosage changes. If this occurs, need an extension of the Cox PHM that allows for time-dependent covariates.

## Data set used for our study

## ##notes for slides  {.scrollable}

-   Methods

    -   dataset

    -   cleaning of data

    -   Methods and results more iterative:

-   Results and Discussion

    -   first model

    -   second model

    -   third model

    -   fourth model

    -   fifth model

-   Conclusion
